version: '3.3'
services:
  torch:
    container_name: torch-cpu
    image: torch-cpu
    build:
      context: .
      dockerfile: Dockerfile-CPU
    entrypoint: bash
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./gcns-fyp
        target: /app/gcns-fyp

